// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeA8VZalBIuNr4F9dm6HLp6Vm7kCCbVY',
    appId: '1:268474549120:web:de0ecbd0f68cc9ac55b765',
    messagingSenderId: '268474549120',
    projectId: 'untitled-3b133',
    authDomain: 'untitled-3b133.firebaseapp.com',
    storageBucket: 'untitled-3b133.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnsaWPAXewUj-Q14for6DSgZ71_5Vq-5g',
    appId: '1:268474549120:android:c882064f7d9aaa9f55b765',
    messagingSenderId: '268474549120',
    projectId: 'untitled-3b133',
    storageBucket: 'untitled-3b133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXD2LZBanY4IbBaM9EaS1gAobaSPql-AU',
    appId: '1:268474549120:ios:08280adeb766918155b765',
    messagingSenderId: '268474549120',
    projectId: 'untitled-3b133',
    storageBucket: 'untitled-3b133.appspot.com',
    iosClientId: '268474549120-gdp5762pgnuf3parnnnt6qiql1j4cbdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXD2LZBanY4IbBaM9EaS1gAobaSPql-AU',
    appId: '1:268474549120:ios:80bd658e16e73c9655b765',
    messagingSenderId: '268474549120',
    projectId: 'untitled-3b133',
    storageBucket: 'untitled-3b133.appspot.com',
    iosClientId: '268474549120-6glrb1jfrfems1oghh7pqfn53prnmeff.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
